# This action updates assets files
name: Assets updater

on:
  # weekly
  schedule:
    - cron: '0 0 * * SUN'

  # manually
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  workingBranch: assets-updater-action

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Git config
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Prepare branch
        run: |
          count=($(git ls-remote --heads origin "$workingBranch" | wc))
          if [[ ${count[0]} -ne 0 ]]; then
            # Exists
            git checkout -b $workingBranch "origin/$workingBranch"
          else
            # Does not exist
            git checkout -b $workingBranch
            git push --set-upstream origin $workingBranch
          fi

      - name: ClearURLs catalog
        continue-on-error: true # just skip the file
        run: |
          bash ./.github/scripts/file-updater.sh $fileName $fileURL $filePath $hashURL
          git add "$filePath$fileName"
          git commit -m "
          $message
          
          File: $filePath$fileName
          Url: $fileURL
          Hash: $hashURL
          "
          
          git push
          echo "$fileName commited successfully"
        env:
          fileName: "data.minify.json"
          fileURL: "https://rules2.clearurls.xyz/data.minify.json"
          filePath: "./app/src/main/assets/"
          hashURL: "https://rules2.clearurls.xyz/rules.minify.hash"
          message: "ClearURLs catalog updated"

      - name: Pull request
        run: |
          commitDiff=($(git diff master...$workingBranch --name-only | wc))
          if [[ ${commitDiff[0]} -ne 0 ]]; then
            # Any difference
            prLs=($(gh pr list --head $workingBranch | wc))
            if [[ ${prLs[0]} -ne 0 ]]; then
              # PR already exists
              echo "PR already exists"
            else
              # PR does not exist
              # Note: If a previous PR is closed but the branch is not deleted, those changes will still be here.
              # It is recommended to delete the branch after closing or merging to keep it clean and up to date.
              gh pr create --title 'Assets updated (automatic action)' --body "$message"
              echo "PR created"
            fi
          else
            # No differences
            git push origin --delete $workingBranch
            echo "Nothing updated, deleting branch on origin"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: "One or more assets were updated.\n\nThis is an automatic PR run from a [github action](../actions/workflows/assets-updater.yml)"
