# This action updates assets files
name: Assets updater

on:
 # weekly
 schedule:
   - cron: '0 0 * * Sun'
    
permissions:
  contents: write
  pull-requests: write

jobs:
  download:
    runs-on: ubuntu-latest

    env:
      workingBranch: assets-updater-action
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check if branch exists
        run: |
          count=($(git ls-remote --heads origin "$workingBranch" | wc))
          if [[ ${count[0]} -ne 0 ]]; then
            # Exists
            git fetch
            git checkout -b $workingBranch "origin/$workingBranch"
          else
            # Does not exist
            git checkout -b $workingBranch
            git push --set-upstream origin $workingBranch
          fi

      - name: ClearURLs catalog
        continue-on-error: true
        run: |
          bash ./.github/scripts/file-updater.sh $fileName $fileURL $filePath $hashURL
          git add "$filePath$fileName"
          git commit -m "$message"
          git push
          echo "$fileName commited successfully"
        env:
          fileName: "data.minify.json"
          fileURL: "https://rules2.clearurls.xyz/data.min.json"
          filePath: "./app/src/main/assets/"
          hashURL: "https://rules2.clearurls.xyz/rules.min.hash"
          message: "ClearURLs catalog updated"

      - name: Pull request
        run:
          gh pr create --title 'Automated assets updater action' --body ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
